import = ["/home/semeninrussia/.config/alacritty/themes/themes/gruvbox_dark.toml"]
# import = ["/home/semeninrussia/.config/alacritty/themes/themes/ toml"]


[window]
padding = { x = 15, y = 0 }
opacity = 0.95

[font]
size = 15.0

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Regular"
