#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 5 6

# Borders
bspc config border_width           2
bspc config left_padding           45
bspc config right_padding          45
bspc config window_gap             15
bspc config active_border_color    "#ffa500" # IDK
bspc config focused_border_color   "#d79921" # orange
bspc config normal_border_color    "#282828" # the same as background
bspc config presel_feedback_color  "#d79921" # orange

# Miscellaneous
bspc config split_ratio            0.681  # golden rantio

# Monocle
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config left_monocle_padding   10
bspc config right_monocle_padding  10
bspc config top_monocle_padding    11
bspc config bottom_monocle_padding 10


# Rules
bspc rule -a Emacs desktop='^4' state="tiled"
bspc rule -a TelegramDesktop desktop='^1' state="tiled"
# i'm using my browser on desktop 2
bspc rule -a GoogleChrome desktop='^2' state="tiled"
bspc rule -a firefox desktop='^2'

# Polybar
#
# settings located inside ~/.config/polybar/
polybar &

# window Manager
#
# Opacity, borders, animations for windows
picom &

# Wallpaper
feh --bg-scale ~/.config/wallpapers/rafael.jpg &
