#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 5 6

# Borders
bspc config border_width         2
bspc config window_gap           15
bspc config active_border_color  "#ffa500"  # IDK
bspc config focused_border_color "#d79921"  # orange
bspc config normal_border_color  "#d5c4a1"  # white

# Miscellaneous
bspc config split_ratio         0.681  # golden rantio
bspc config borderless_monocle  false
bspc config gapless_monocle     true

# Rules
bspc rule -a Emacs desktop='^4' state="tiled"
# i'm using my browser on desktop 2
bspc rule -a google-chrome-stable desktop='^2'
bspc rule -a firefox desktop='^2'
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Polybar
#
# settings located inside ~/.config/polybar/
polybar &

# window Manager
#
# Opacity, borders, animations for windows
picom &

# Wallpaper
feh --bg-scale ~/.config/wallpapers/rafael.jpg &
